version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - broker_adaptor
      
  grafana:
    image: 127.0.0.1:5000/sprc3_grafana
    ports:
      - 80:3000
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: asistent
      GF_SECURITY_ADMIN_PASSWORD: grafanaSPRC2021
    networks:
      - influx_grafana

  influxdb:
    image: influxdb:1.7
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: db1
    networks:
      - adaptor_influx
      - influx_grafana

  adaptor:
    image: 127.0.0.1:5000/sprc3_adaptor
    networks:
      - broker_adaptor
      - adaptor_influx

networks:
  broker_adaptor:
  adaptor_influx:
  influx_grafana:

volumes:
  grafana-volume:
  influxdb-volume:
